### ISSUE TITLE
testsuite expects font to be installed

### ISSUE THREAD

**Issue by clinty** [LambdaHack/LambdaHack#202] opened 2020-06-15 17:40 UTC
`test: user error (Font file does not exist: /usr/share/lambdahack/GameDefinition/fonts/16x16xw.bdf)`

The testsuite runs without setting the font dir to the location of fonts in the source directory, so the test fails without the fonts having been installed.

**Comment by Mikolaj** [comment] 2020-06-15 17:46
Hi, thanks for the report. How do you install the game and how to do you run tests? Is it Linux? From source or package? What distro?

**Comment by Mikolaj** [comment] 2020-06-15 17:50
Oh, I see, Debian, isnt' it? 0.9.5.0-1? All archs or just some? Let me look for the bug in the Debian dev corner...

**Comment by Mikolaj** [comment] 2020-06-15 17:52
Got it: https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/haskell-lambdahack.html

**Comment by Mikolaj** [comment] 2020-06-15 18:00
I remember I specifically added checking the fonts accessibility to the test suite. I wanted to make sure users can find the fonts, because I've had a report the font was missing for someone. 

So, you are saying, when the test is run, the font is not yet installed? That's a pity, because it means I can't test if the fonts are properly installed. Is there a way to remedy that? If the package is built with cabal or stack, whether in-place or specially, the font is always available. Is that not possible here? Is this some special kind of build?

**Comment by Mikolaj** [comment] 2020-06-15 18:31
Oh, I see

/home/mikolaj/r/DHG_packages/p/haskell-lambdahack/debian/lambdahack.install 

doesn't yet know about this new font. Let me add it and see if it's enough.

**Comment by Mikolaj** [comment] 2020-06-15 19:06
@clinty: I've updated /home/mikolaj/r/DHG_packages/p/haskell-lambdahack/debian/lambdahack.install

If this works, I will similarly update the packaging for Allure.

**Comment by clinty** [comment] 2020-06-15 20:59
@Mikolaj it's being run from Setup.hs.  You should be able to achieve the equivalent by doing a `cabal v1-test` in the source directory in an environment that doesn't have the fonts installed.  Thanks for fixing the .install file but it won't solve this particular issue.

**Comment by Mikolaj** [comment] 2020-06-15 21:37
I see. The only option to make it work without changing source code would to, before the test is run, create a `~/.LambdaHack/config.ui.ini` file that overwrites the font location. But I don't know if I can copy that file from somewhere and also I need to know and provide an absolute paths for the fonts, relative path would not work.

An alternative is to wait for 0.10.0.0 release, probably in a couple of weeks, in which I disable the test (created specially for Debian :) ) or add a fallback to in-source location of the font, assuming the test is run in the directory that contains the .cabal file. And for now we could disable the tests, to sort out any other problems, e.g., deps, that are very likely to affect 0.10.0.0 as well.

What would you advice?

**Comment by clinty** [comment] 2020-06-15 22:10
In-source fallback sounds good, and we can disable the test in the meantime.  I assumed we could just add a --fontDir setting to args2 but obviously I misunderstood something.

**Comment by Mikolaj** [comment] 2020-06-15 22:21
Yes, `--fontDir` in `args2` would definitely work, even with the relative path as in `--fontDir GameDefinition/fonts", but I have no clue how to patch code via Debian scripts. I'd gladly learn by example. :)

**Comment by clinty** [comment] 2020-06-15 22:28
You would put a quilt patch in debian/patches , but when I try this I get

`option --fontDir: cannot parse value `GameDefinition/fonts'`

Any idea why?

**Comment by Mikolaj** [comment] 2020-06-15 22:54
Strangely, it needs extra double quotes (somebody's apparently fixed that for 0.10 so I didn't notice:

        let args2 = words "--fontDir \"GameDefinition/fonts\" --dbgMsgSer --logPriority 0 --newGame 3 --maxFps 100000 --benchmark --stopAfterFrames 50 --automateAll --keepAutomated --gameMode battle --setDungeonRng 7 --setMainRng 7"

**Comment by clinty** [comment] 2020-06-15 23:21
That works.  I'll push the fix so you can take a look when salsa is reachable again.

**Comment by Mikolaj** [comment] 2020-06-15 23:45
Thank's a lot! I will this patching myself for Allure, if needed. Also, I've just added the argument to the tests permanently in 0.10.0.0 --- the test is for Debian anyway, and in CI I run tests from the top of the source tree as well.

**Comment by Mikolaj** [comment] 2020-08-20 19:03
I think this is finally working fine for both LambdaHack and Allure in Debian. Thank you very much! Closing.

**Closed by Mikolaj** 2020-08-20 19:03 UTC
