### ISSUE TITLE
Can't install LambdaHack via Cabal: ExitFailure 1; No instance for (Applicative Frequency)

### ISSUE THREAD

**Issue by digitator** [LambdaHack/LambdaHack#92] opened 2015-04-23 14:18 UTC
Trying to install LambdaHack in a sandbox results in ExitFailure 1, it appears that there's some problem with the Frequency utils. This is on 64 bit GNU/Linux.
```
Resolving dependencies...
Notice: installing into a sandbox located at
/(...)/.cabal-sandbox
Downloading LambdaHack-0.2.6...
Configuring LambdaHack-0.2.6...
Building LambdaHack-0.2.6...
Failed to install LambdaHack-0.2.6
Build log ( /(...)/.cabal-sandbox/logs/LambdaHack-0.2.6.log ):
Configuring LambdaHack-0.2.6...
Building LambdaHack-0.2.6...
Preprocessing library LambdaHack-0.2.6...
[ 1 of 70] Compiling Game.LambdaHack.Utils.LQueue ( Game/LambdaHack/Utils/LQueue.hs, dist/dist-sandbox-a99f07ee/build/Game/LambdaHack/Utils/LQueue.o )
[ 2 of 70] Compiling Game.LambdaHack.Color ( Game/LambdaHack/Color.hs, dist/dist-sandbox-a99f07ee/build/Game/LambdaHack/Color.o )
[ 3 of 70] Compiling Game.LambdaHack.Flavour ( Game/LambdaHack/Flavour.hs, dist/dist-sandbox-a99f07ee/build/Game/LambdaHack/Flavour.o )
[ 4 of 70] Compiling Paths_LambdaHack ( dist/dist-sandbox-a99f07ee/build/autogen/Paths_LambdaHack.hs, dist/dist-sandbox-a99f07ee/build/Paths_LambdaHack.o )
[ 5 of 70] Compiling Game.LambdaHack.Time ( Game/LambdaHack/Time.hs, dist/dist-sandbox-a99f07ee/build/Game/LambdaHack/Time.o )
[ 6 of 70] Compiling Game.LambdaHack.Misc ( Game/LambdaHack/Misc.hs, dist/dist-sandbox-a99f07ee/build/Game/LambdaHack/Misc.o )
[ 7 of 70] Compiling Game.LambdaHack.Content.FactionKind ( Game/LambdaHack/Content/FactionKind.hs, dist/dist-sandbox-a99f07ee/build/Game/LambdaHack/Content/FactionKind.o )
[ 8 of 70] Compiling Game.LambdaHack.CDefs ( Game/LambdaHack/CDefs.hs, dist/dist-sandbox-a99f07ee/build/Game/LambdaHack/CDefs.o )
[ 9 of 70] Compiling Game.LambdaHack.Content.PlaceKind ( Game/LambdaHack/Content/PlaceKind.hs, dist/dist-sandbox-a99f07ee/build/Game/LambdaHack/Content/PlaceKind.o )
[10 of 70] Compiling Game.LambdaHack.Utils.File ( Game/LambdaHack/Utils/File.hs, dist/dist-sandbox-a99f07ee/build/Game/LambdaHack/Utils/File.o )
[11 of 70] Compiling Game.LambdaHack.Utils.Assert ( Game/LambdaHack/Utils/Assert.hs, dist/dist-sandbox-a99f07ee/build/Game/LambdaHack/Utils/Assert.o )
[12 of 70] Compiling Game.LambdaHack.PointXY ( Game/LambdaHack/PointXY.hs, dist/dist-sandbox-a99f07ee/build/Game/LambdaHack/PointXY.o )
[13 of 70] Compiling Game.LambdaHack.VectorXY ( Game/LambdaHack/VectorXY.hs, dist/dist-sandbox-a99f07ee/build/Game/LambdaHack/VectorXY.o )
[14 of 70] Compiling Game.LambdaHack.Area ( Game/LambdaHack/Area.hs, dist/dist-sandbox-a99f07ee/build/Game/LambdaHack/Area.o )
[15 of 70] Compiling Game.LambdaHack.FOV.Common ( Game/LambdaHack/FOV/Common.hs, dist/dist-sandbox-a99f07ee/build/Game/LambdaHack/FOV/Common.o )
[16 of 70] Compiling Game.LambdaHack.FOV.Digital ( Game/LambdaHack/FOV/Digital.hs, dist/dist-sandbox-a99f07ee/build/Game/LambdaHack/FOV/Digital.o )
[17 of 70] Compiling Game.LambdaHack.FOV.Permissive ( Game/LambdaHack/FOV/Permissive.hs, dist/dist-sandbox-a99f07ee/build/Game/LambdaHack/FOV/Permissive.o )
[18 of 70] Compiling Game.LambdaHack.FOV.Shadow ( Game/LambdaHack/FOV/Shadow.hs, dist/dist-sandbox-a99f07ee/build/Game/LambdaHack/FOV/Shadow.o )
[19 of 70] Compiling Game.LambdaHack.Utils.Frequency ( Game/LambdaHack/Utils/Frequency.hs, dist/dist-sandbox-a99f07ee/build/Game/LambdaHack/Utils/Frequency.o )

Game/LambdaHack/Utils/Frequency.hs:26:10:
    No instance for (Applicative Frequency)
      arising from the superclasses of an instance declaration
    In the instance declaration for ‘Monad Frequency’

Game/LambdaHack/Utils/Frequency.hs:33:10:
    No instance for (GHC.Base.Alternative Frequency)
      arising from the superclasses of an instance declaration
    In the instance declaration for ‘MonadPlus Frequency’
cabal: Error: some packages failed to install:
LambdaHack-0.2.6 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by Mikolaj** [comment] 2015-04-23 14:24
You apparently try to install a very old version. I should add a hint about `cabal update` to the README. Could you try if it helps?

**Comment by digitator** [comment] 2015-04-23 15:45
I have ran `cabal update` right before attempting to install LambdaHack. I tried running it again, but it didn't change the result. I should note that before this, I had to run `cabal install gtk2hs-buildtools`, `cabal install cairo` and `cabal install pretty-show`, (in that order) since the previous steps of the installation were failing with information that the mentioned packages were missing.

**Comment by Mikolaj** [comment] 2015-04-23 18:36
OK, so that sounds serious. Could you run `cabal install -v2 LambdaHack-0.4.101.1 >& log` and send me the output (e.g. via http://gist.github.com)? Thank you!

**Comment by Mikolaj** [comment] 2015-04-23 18:38
One more thing you may try `cabal install cabal-install-1.22.2.0` and if it fails, please send me the `-v2` log as well.

**Comment by digitator** [comment] 2015-04-23 20:50
`cabal install cabal-install-1.22.2.0` ran without any problems. I'm not sure how to send the output to you specifically, but I've uploaded the log of `cabal install -v2 LambdaHack-0.4.101.1 >& log` to gist: gist.github.com/digitator/18714d998096d0c44f57 .

**Comment by Mikolaj** [comment] 2015-04-23 21:02
That did the trick, thank you. I see the problem is that the newest version of package `hsini` that works with GHC 7.10.1 is not yet released to hackage. So you need to install the version from `https://github.com/magthe/hsini` first (`git clone`, `cabal install`).

**Comment by digitator** [comment] 2015-04-25 11:05
I can confirm that the install succeeded after doing `git clone` then `cabal install hsini/hsini.cabal', then `cabal install lambdahack`. I can run LambdaHack and import the modules.
Maybe this problem should be mentioned somewhere in the documentation.

**Comment by Mikolaj** [comment] 2015-04-25 17:39
Great. Instead, I'm pleading with the hsini maintainer to release the new version to hackage. GHC 7.10 is still rather bleeding edge. Myself, I'm using GHC 7.8 and, in particular, I haven't gotten rid of 7.10 warnings yet (I plan to by using https://github.com/sol/base-compat througout the code). But if the problem isn't gone by the time I'm releasing LH 0.5 (in a couple of weeks, I guess), I will indeed describe the workaround in the README. Thanks again.

**Comment by magthe** [comment] 2015-04-25 18:41
There's a release 0.4.1 of `hsini` on Hackage now.

**Comment by Mikolaj** [comment] 2015-04-26 20:39
@magthe: Thank you. It works OK: picks hsini-0.4.2 for GHC 7.10 and hsini-0.4.1 for GHC 7.8. Closing the issue.

**Closed by Mikolaj** 2015-04-26 20:39 UTC
